version: '3.4'
services:
  service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      APP_ENV: ${APP_ENV:-development}
    volumes:
      - ./:/app
      - ./docker/start_service.sh:/start_service.sh
    ports:
      - 5036:8000
      - 5778:5678
    command: bash /start_service.sh