[tool.poetry]
name = "validator-service"
version = "0.1.0"
description = "Validating emails and such"
authors = ["Tobias Jeppesen <github@tobiasjeppesen.com>"]

[tool.poetry.dependencies]
python = "^3.9"
connexion = "^2.7.0"
email-validator = "^1.1.2"
phonenumbers = "^8.12.19"
Flask-Cors = "^3.0.10"
gunicorn = "^20.0.4"
bankkonto = {git = "https://github.com/zensum/bankkonto.git"}

[tool.poetry.dev-dependencies]
mypy = "^0.812"
flake8 = "^3.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
