openapi: 3.0.0
info:
  title: Validator Service
  version: 1.0.0
  description: Service for validating emails and such
  contact:
    email: dev@zensum.se

servers:
  - url: /
    description: This server

paths:
  /:
    post:
      description: Validate email or phone number
      operationId: api.validate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              oneOf:
                - required: [pni]
                - required: [email]
                - required: [phone_number]
                - required: [account]
              properties:
                email:
                  type: string
                  example: dev@zensum.se
                phone_number:
                  type: string
                  description: Phone number to validate
                  example: 0771304448
                account:
                  type: object
                  additionalProperties: false
                  required:
                    - "account_number"
                  properties:
                    clearing_number:
                      type: string
                      example: "1234"
                      nullable: true
                    account_number:
                      type: string
                      example: "1234567"
                    bank_id:
                      type: integer
                      example: 23
                    bank_name:
                      type: string
                      example: SEB
                      description: Bank name
                    country_code:
                      enum: ["SE", "NO"]
                      description: The country the payload is supposed to validate for
                pni:
                  type: string
                  example: "194102137785"
                  description: Personal national identifier

      responses:
        '200':
          description: Valid payload
          content:
            application/json:
              schema:
                $ref: '#components/schemas/ValidResponse'
        '400':
          description: Invalid payload
          content:
            application/json:
              schema:
                $ref: '#components/schemas/InvalidResponse'

components:
  schemas:
    ValidResponse:
      type: object
      additionalProperties: false
      required:
        - valid
      properties:
        valid:
          type: boolean
          description: If the validation was valid
          example: true
          enum: [true]
          nullable: false
        formatted:
          type: string
          description: The formatted value of the sent property
          nullable: false
    InvalidResponse:
      type: object
      additionalProperties: false
      required:
        - valid
        - message
        - formatted
      properties:
        valid:
          type: boolean
          description: If the validation was not valid
          example: false
          enum: [false]
          nullable: false
        message:
          type: string
          description: Message of why it was not valid
          example: The email is not valid
          nullable: false
        formatted:
          type: string
          description: The formatted value of the sent property
          nullable: true